"use client";

import {
  Clock, Brain, Database, Search, Shield, Zap,
  GitBranch, BarChart3, FileSearch,
} from "lucide-react";

const features = [
  {
    icon: <Clock size={22} />,
    title: "Time-Aware Retrieval",
    desc: "Every query is filtered by date. Documents are only returned if they were valid on your specified date — no stale results ever.",
    color: "#A855F7",
    bg: "rgba(168, 85, 247, 0.1)",
    border: "rgba(168, 85, 247, 0.15)",
  },
  {
    icon: <Brain size={22} />,
    title: "Gemini 2.5 Flash LLM",
    desc: "Answers generated by Google's latest model using only retrieved context. No hallucinations from outside knowledge.",
    color: "#06B6D4",
    bg: "rgba(6, 182, 212, 0.1)",
    border: "rgba(6, 182, 212, 0.15)",
  },
  {
    icon: <Database size={22} />,
    title: "PostgreSQL + FAISS",
    desc: "Metadata and full-text search powered by PostgreSQL with GIN indexes. Vector search via FAISS for semantic similarity.",
    color: "#10B981",
    bg: "rgba(16, 185, 129, 0.1)",
    border: "rgba(16, 185, 129, 0.15)",
  },
  {
    icon: <Search size={22} />,
    title: "Hybrid Search",
    desc: "Combines semantic vector search with PostgreSQL full-text search for best-of-both results with configurable weights.",
    color: "#F59E0B",
    bg: "rgba(245, 158, 11, 0.1)",
    border: "rgba(245, 158, 11, 0.15)",
  },
  {
    icon: <GitBranch size={22} />,
    title: "Document Versioning",
    desc: "Track policy changes over time. Create new versions, compare diffs, and always retrieve the version valid on your query date.",
    color: "#A855F7",
    bg: "rgba(168, 85, 247, 0.1)",
    border: "rgba(168, 85, 247, 0.15)",
  },
  {
    icon: <Zap size={22} />,
    title: "Redis Caching",
    desc: "Identical queries are served from Redis cache in milliseconds. Automatic invalidation when documents are updated.",
    color: "#06B6D4",
    bg: "rgba(6, 182, 212, 0.1)",
    border: "rgba(6, 182, 212, 0.15)",
  },
  {
    icon: <Shield size={22} />,
    title: "API Key Auth + Rate Limiting",
    desc: "Every endpoint is protected with API key authentication. Rate limiting at 20 req/min prevents abuse.",
    color: "#10B981",
    bg: "rgba(16, 185, 129, 0.1)",
    border: "rgba(16, 185, 129, 0.15)",
  },
  {
    icon: <FileSearch size={22} />,
    title: "Smart PDF Upload",
    desc: "AI automatically extracts effective dates and expiry dates from uploaded PDFs. No manual date entry needed.",
    color: "#F59E0B",
    bg: "rgba(245, 158, 11, 0.1)",
    border: "rgba(245, 158, 11, 0.15)",
  },
  {
    icon: <BarChart3 size={22} />,
    title: "RAG Evaluation Suite",
    desc: "44 automated tests covering retrieval accuracy, time relevance (100%), keyword match, and response time benchmarks.",
    color: "#A855F7",
    bg: "rgba(168, 85, 247, 0.1)",
    border: "rgba(168, 85, 247, 0.15)",
  },
];

export default function Features() {
  return (
    <section style={{ padding: "80px 24px" }}>
      <div style={{ maxWidth: "1100px", margin: "0 auto" }}>

        {/* Header */}
        <div style={{ textAlign: "center", marginBottom: "64px" }}>
          <div
            style={{
              display: "inline-block",
              padding: "4px 14px",
              borderRadius: "100px",
              background: "rgba(124, 58, 237, 0.1)",
              border: "1px solid rgba(124, 58, 237, 0.2)",
              fontSize: "0.75rem",
              color: "#A855F7",
              fontWeight: 600,
              textTransform: "uppercase",
              letterSpacing: "0.1em",
              marginBottom: "16px",
            }}
          >
            Features
          </div>
          <h2
            style={{
              fontFamily: "Syne, sans-serif",
              fontSize: "clamp(1.8rem, 4vw, 2.8rem)",
              fontWeight: 800,
              color: "#F0F0FF",
              marginBottom: "16px",
            }}
          >
            Everything you need for{" "}
            <span className="text-gradient">temporal RAG</span>
          </h2>
          <p style={{ color: "#6B7280", fontSize: "1rem", maxWidth: "500px", margin: "0 auto" }}>
            Built with production-grade infrastructure. Not a toy demo.
          </p>
        </div>

        {/* Grid */}
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
            gap: "20px",
          }}
        >
          {features.map((f, i) => (
            <div
              key={i}
              style={{
                background: "#16181D",
                border: `1px solid ${f.border}`,
                borderRadius: "14px",
                padding: "24px",
                transition: "transform 0.2s, box-shadow 0.2s",
                cursor: "default",
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.transform = "translateY(-2px)";
                e.currentTarget.style.boxShadow = `0 8px 30px rgba(0,0,0,0.3)`;
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.transform = "translateY(0)";
                e.currentTarget.style.boxShadow = "none";
              }}
            >
              <div
                style={{
                  width: "44px",
                  height: "44px",
                  borderRadius: "10px",
                  background: f.bg,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  color: f.color,
                  marginBottom: "16px",
                }}
              >
                {f.icon}
              </div>
              <h3
                style={{
                  fontFamily: "Syne, sans-serif",
                  fontSize: "1rem",
                  fontWeight: 700,
                  color: "#F0F0FF",
                  marginBottom: "8px",
                }}
              >
                {f.title}
              </h3>
              <p style={{ fontSize: "0.875rem", color: "#6B7280", lineHeight: 1.6 }}>
                {f.desc}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}